#!/bin/bash

set -e

REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
BUILD_DIR=$REPO_DIR/build
KEXT_PATH=$BUILD_DIR/Debug/softu2f.kext

if [ -d $KEXT_PATH ] && [ ! -w $KEXT_PATH ]; then
  echo "softu2f.kext owned by root. Removing before build."
  sudo rm -rf $KEXT_PATH
fi

echo "Building softu2f.kext"
if ! xcodebuild -scheme Driver SYMROOT=$BUILD_DIR &> /dev/null; then
  echo "Error building softu2f.kext"
  exit 1
fi
echo "Built softu2f.kext"
